### ISSUE TITLE
Cant generate final mesh object

### ISSUE THREAD

**Issue by AlienXtream** [MaximeHerpin/modular_tree#194]
i cant generate the final mesh with the nodes i have. idk if ive done something wrong of if its broken or what but i get a python error. heres a screen shot (edited to redact personal info)
![image](https://user-images.githubusercontent.com/12606809/67992310-53a01100-fc90-11e9-84ee-5daa4a891b35.png)

error log too 
Traceback (most recent call last):
  File "C:\Users\X\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\modular_tree-blender_28\nodes\tree_parameters_node.py", line 421, in execute
    node.execute()
  File "C:\Users\X\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\modular_tree-blender_28\nodes\tree_parameters_node.py", line 87, in execute
    tree_ob = generate_tree_object(tree_ob, tree, self.resolution)
  File "C:\Users\X\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\modular_tree-blender_28\nodes\tree_parameters_node.py", line 195, in generate_tree_object
    verts, faces, radii, uvs, bone_weights = tree.build_mesh_data(resolution) # tree mesh data
  File "C:\Users\X\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\modular_tree-blender_28\tree.py", line 23, in build_mesh_data
    build_module_rec(self.stem, resolution, verts, faces, uvs, weights, bone_weights)
  File "C:\Users\X\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\modular_tree-blender_28\geometry.py", line 103, in build_module_rec
    build_module_rec(child, output_resolutions[i], verts, faces, uvs, weights, bone_weights, output_loops[i], uv_height)
  File "C:\Users\X\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\modular_tree-blender_28\geometry.py", line 103, in build_module_rec
    build_module_rec(child, output_resolutions[i], verts, faces, uvs, weights, bone_weights, output_loops[i], uv_height)
  File "C:\Users\X\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\modular_tree-blender_28\geometry.py", line 103, in build_module_rec
    build_module_rec(child, output_resolutions[i], verts, faces, uvs, weights, bone_weights, output_loops[i], uv_height)
  File "C:\Users\X\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\modular_tree-blender_28\geometry.py", line 64, in build_module_rec
    wrap_circle(child_verts, child_dir, Vector((0,0,1)), node.radius) # wrap child verts around module cylinder
  File "C:\Users\X\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\modular_tree-blender_28\geometry.py", line 169, in wrap_circle
    v -= ((1-sqrt(1 - c**2)) * wrap_rad) * circle_dir
ValueError: math domain error

location: <unknown location>:-1

**Comment by MaximeHerpin** [comment]
Fixed in latest version !

**Comment by AlienXtream** [comment]
oh.... nice.... better late than never :P

**Comment by MaximeHerpin** [comment]
Yeah, sorry about that :D
