### ISSUE TITLE
Blender 2.90 - cannot import name 'nodes_classes' from 'modular_tree-blender_28.nodes'

### ISSUE THREAD

**Issue by metal3d** [MaximeHerpin/modular_tree#231]
Using the blender_280 branch on Blender 2.90, I have an error when I try to activate the addon.

```
Traceback (most recent call last):
  File "/home/metal3d/Apps/blender-2.90.0-linux64/2.90/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/home/metal3d/.config/blender/2.90/scripts/addons/modular_tree-blender_28/__init__.py", line 26, in <module>
    from .nodes import nodes_classes
ImportError: cannot import name 'nodes_classes' from 'modular_tree-blender_28.nodes' (/home/metal3d/.config/blender/2.90/scripts/addons/modular_tree-blender_28/nodes.py)
```

I tried to find why... but no reason. `node_classes` should exists

**Comment by MaximeHerpin** [comment]
Fixed in latest version !
