### ISSUE TITLE
multiple python errors

### ISSUE THREAD

**Issue by doktourtv** [MaximeHerpin/modular_tree#275]
C:\Users\julian\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\modular_tree-blender_28\addon_updater_ops.py:911
Python: Traceback (most recent call last):
  File "C:\Users\julian\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\modular_tree-blender_28\addon_updater_ops.py", line 234, in execute
    updater.set_check_interval(enable=settings.auto_check_update,
  File "C:\Users\julian\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\modular_tree-blender_28\addon_updater.py", line 511, in set_check_interval
    raise ValueError("Enable must be a boolean value")
ValueError: Enable must be a boolean value

location: <unknown location>:-1
Error: Python: Traceback (most recent call last):
  File "C:\Users\julian\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\modular_tree-blender_28\addon_updater_ops.py", line 234, in execute
    updater.set_check_interval(enable=settings.auto_check_update,
  File "C:\Users\julian\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\modular_tree-blender_28\addon_updater.py", line 511, in set_check_interval
    raise ValueError("Enable must be a boolean value")
ValueError: Enable must be a boolean value

location: <unknown location>:-1

rna_uiItemR: property not found: Preferences.auto_check_update

C:\Users\julian\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\modular_tree-blender_28\addon_updater_ops.py:896
rna_uiItemR: property not found: Preferences.updater_intrval_months

C:\Users\julian\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\modular_tree-blender_28\addon_updater_ops.py:905
rna_uiItemR: property not found: Preferences.updater_intrval_days

C:\Users\julian\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\modular_tree-blender_28\addon_updater_ops.py:907
rna_uiItemR: property not found: Preferences.updater_intrval_hours

C:\Users\julian\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\modular_tree-blender_28\addon_updater_ops.py:909
rna_uiItemR: property not found: Preferences.updater_intrval_minutes

C:\Users\julian\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\modular_tree-blender_28\addon_updater_ops.py:911

C:\Users\julian\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\modular_tree-blender_28\addon_updater_ops.py:911
Python: Traceback (most recent call last):
  File "C:\Users\julian\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\modular_tree-blender_28\addon_updater_ops.py", line 234, in execute
    updater.set_check_interval(enable=settings.auto_check_update,
  File "C:\Users\julian\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\modular_tree-blender_28\addon_updater.py", line 511, in set_check_interval
    raise ValueError("Enable must be a boolean value")
ValueError: Enable must be a boolean value

location: <unknown location>:-1
Error: Python: Traceback (most recent call last):
  File "C:\Users\julian\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\modular_tree-blender_28\addon_updater_ops.py", line 234, in execute
    updater.set_check_interval(enable=settings.auto_check_update,
  File "C:\Users\julian\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\modular_tree-blender_28\addon_updater.py", line 511, in set_check_interval
    raise ValueError("Enable must be a boolean value")
ValueError: Enable must be a boolean value

location: <unknown location>:-1

rna_uiItemR: property not found: Preferences.auto_check_update

C:\Users\julian\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\modular_tree-blender_28\addon_updater_ops.py:896
rna_uiItemR: property not found: Preferences.updater_intrval_months

C:\Users\julian\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\modular_tree-blender_28\addon_updater_ops.py:905
rna_uiItemR: property not found: Preferences.updater_intrval_days

C:\Users\julian\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\modular_tree-blender_28\addon_updater_ops.py:907
rna_uiItemR: property not found: Preferences.updater_intrval_hours

C:\Users\julian\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\modular_tree-blender_28\addon_updater_ops.py:909
rna_uiItemR: property not found: Preferences.updater_intrval_minutes

C:\Users\julian\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\modular_tree-blender_28\addon_updater_ops.py:911

**Comment by BriAri1** [comment]
As per user Yafu try using the updated files they edited. 
https://blenderartists.org/t/modular-tree/674043/923

**Comment by MaximeHerpin** [comment]
Fixed in latest version.
