### ISSUE TITLE
Add on wont find an update in 2.93, here's error code.

### ISSUE THREAD

**Issue by llcaptainmorgan** [MaximeHerpin/modular_tree#303]
Python: Traceback (most recent call last):
  File "C:\Users\jesse\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\modular_tree-blender_28\addon_updater_ops.py", line 234, in execute
    updater.set_check_interval(enable=settings.auto_check_update,
  File "C:\Users\jesse\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\modular_tree-blender_28\addon_updater.py", line 511, in set_check_interval
    raise ValueError("Enable must be a boolean value")
ValueError: Enable must be a boolean value

location: <unknown location>:-1

**Comment by MaximeHerpin** [comment]
Fixed with latest version.
