### ISSUE TITLE
Python: Traceback (most recent call last):   File "C:\Users\wadam\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\modular_tree-blender_28\addon_updater_ops.py", line 234, in execute     updater.set_check_interval(enable=settings.auto_check_update,   File "C:\Users\wadam\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\modular_tree-blender_28\addon_updater.py", line 511, in set_check_interval     raise ValueError("Enable must be a boolean value") ValueError: Enable must be a boolean value  location: <unknown location>:-1

### ISSUE THREAD

**Issue by iifufu** [MaximeHerpin/modular_tree#345]

**Comment by timothyj6767** [comment]
I get this same error using blender 3.1
The nodes have no settings

**Comment by GitHubRGB-sadness** [comment]
Same error using 3.3.1 can even see settings for nodes and cant see the presets
