### ISSUE TITLE
Adjustments to work with Blender 3.1 and 3.2

### ISSUE THREAD

**Issue by steven-ray** [MaximeHerpin/modular_tree#356]
For this add-on to work with Blender 3.1, it needs to be rebuilt with bindings to python 3.10.x rather than 3.9.x.  With the release of Blender 3.2, geometry nodes deprecates legacy nodes causing the add leaves functionality to be broken.

For those interested, I had rebuilt the master branch for Windows platform last month with python 3.10.4 bindings for Blender 3.1 compatibility. Today I updated the geometry node library for leaves eliminating the deprecated nodes and utilizing the newer nodes instead allowing the leaves functionality to work in Blender 3.2 (this updates the `leaves_distribution` node group in the modular_tree/resources/geo_node/geo_nodes_2_93.blend file from this repo).  Note that though this updated file is still named with 2_93 in the name, it won't work with older versions of Blender that don't support the new nodes.

[modular_tree_4_0_2b_windows.zip](https://github.com/MaximeHerpin/modular_tree/files/8988333/modular_tree_4_0_2b_windows.zip)

**Comment by steven-ray** [comment]
Minor adjustment: This will check blender version and use legacy geometry nodes of version is less than 3.2.  If 3.2 or greater, will use new geometry nodes.  This keeps a bit more backwards compatibility.

[modular_tree_4_0_2c_windows.zip](https://github.com/MaximeHerpin/modular_tree/files/8989346/modular_tree_4_0_2c_windows.zip)

Setting up a fork at https://github.com/steven-ray/modular_tree so I can track my changes.

**Comment by NickHHSgt** [comment]
Downloaded your files. Thought I can simply install them like an addon. Didn’t work. What am I supposed to do with these ?

**Comment by steven-ray** [comment]
What didn't work?  Should install the .zip file just as other add-ons (edit->preferences->add-ons->install... button).  Once added, you should see an addon listed as "Generic: Modular Tree".  Check the checkmark box to enable.  Once installed, this adds a window pane type of Mtree where you can create nodes to make trees.  If you haven't used version 4 before, you can check out youtube (e.g. https://youtu.be/j-944779t84).

My changes is just to fix breaks with Blender 3.1 & 3.2 (Author's release works with up to Blender 3.0).  Outside of that, I have not added any new functionality.

**Comment by steven-ray** [comment]
FYI, for anyone interested, in my fork (https://github.com/steven-ray/modular_tree), I now have built releases with these changes for windows, linux, and both x86 and M1 Macs.

**Comment by NickHHSgt** [comment]
![Uploading 16E30E30-72B8-485D-BC34-2BE7D24F368A.jpeg…]()

**Comment by NickHHSgt** [comment]
I get this error message. 

Python :Traceback (most recent call last): 

File „C:\Program Files\ Blender Foundation\Blender 3.2\3.2\scripts\startup\bl_operator\userpref.py“ , line 50 , in_module_filesystem_remove shutil.rmtree(f_full)

File „C:\Program Files\ Blender Foundation\Blender 3.2\3.2\scripts\startup\bl_operator\userpref.py“ , line 739 , in rmtree return.rmtree_unsafe(path, onerror)


File „C:\Program Files\ Blender Foundation\Blender 3.2\3.2\scripts\startup\bl_operator\userpref.py“ , line 617 , in rmtree oneerror(os.unlink, fullname, sys.exc_info())

File „C:\Program Files\ Blender Foundation\Blender 3.2\3.2\scripts\startup\bl_operator\userpref.py“ , line 615 , in rmtree  in rmtree oneerror(os.unlink, fullname)

**Comment by NickHHSgt** [comment]
I have blender 3.2 installed. Other addons work just fine.

**Comment by NickHHSgt** [comment]
Have a typo in the error message. The last two lines are missing „unsafe“ right between „rmtree“ and „oneerror“

**Comment by steven-ray** [comment]
Hmm, interesting.  If you get this while trying to install, it looks like blender it trying to clean out a previous install.  I have seen when uninstalling mtree that uninstalls fail on windows sometimes because the compiled m_tree.cp39-win_amd64.pyd (or m_tree.cp310-win_amd64.pyd) is loaded by python and considered in use, so it can't be deleted by the shutil.rmtree function.  Don't know how to fix that, but I manually go into C:\Users\<user>\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons and delete the modular_tree folder (when blender is not running).  This effectively uninstalls it.  You might check to see if there's a previous version in your scripts\addons folder and manually delete, then try to install again.

**Comment by NickHHSgt** [comment]
That did it for me. Thank you very much 
🤜🤛

**Comment by ecker00** [comment]
@steven-ray I can't seem to open a new issue in your fork repo.

When I download your fork, install the addon then click to enable it, I get:
```
Modules Installed (modular_tree-master) from '…\\modular_tree.zip' into '…\\AppData\\Roaming\\Blender Foundation\\Blender\\3.2\\scripts\\addons'
Traceback (most recent call last):
  File "…\Blender\3.2\scripts\modules\addon_utils.py", line 335, in enable
    mod = __import__(module_name)
  File "…\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\modular_tree-master\__init__.py", line 16, in <module>
    from . import python_classes
  File "…\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\modular_tree-master\python_classes\__init__.py", line 2, in <module>
    from . import nodes
  File "…\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\modular_tree-master\python_classes\nodes\__init__.py", line 6, in <module>
    from . import sockets
  File "…\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\modular_tree-master\python_classes\nodes\sockets\__init__.py", line 6, in <module>
    from .property_socket import MtreePropertySocket
  File "…\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\modular_tree-master\python_classes\nodes\sockets\property_socket.py", line 3, in <module>
    from ....m_tree import ConstantProperty, RandomProperty, PropertyWrapper
ImportError: cannot import name 'ConstantProperty' from 'modular_tree-master.m_tree' (unknown location)
```
(just striped our personal paths with …)

**Comment by steven-ray** [comment]
Hi ecker00,

I have enabled the issues tab in my fork of this repo.  In looking at your log, I see part of the path includes`modular_tree-master`.  This tells me you probably downloaded the .zip file of the entire repo from github (using the "download .zip" from the green "Code" button on the main page).  This will get you the entire repo (unbuilt) which won't work in blender as is (you would need to build it and package it first).

I recommend removing that from blender, then going to the releases page at https://github.com/steven-ray/modular_tree/releases and download one of the appropriate built releases from there (e.g. modular_tree_4_0_2_1a_windows.zip) and try installing/enabling that.

Hope that helps!

**Comment by ecker00** [comment]
Ah sorry, what a silly mistake! (Not the first time I've done that with an add-on! 🤣) But was thinking that maybe the "releases" wasn't updated as it was a fork. Thank you for swift response, amazing that you've picked up maintenance on this project. 🙌✨🎉

**Comment by marauder2k7** [comment]
> Minor adjustment: This will check blender version and use legacy geometry nodes of version is less than 3.2. If 3.2 or greater, will use new geometry nodes. This keeps a bit more backwards compatibility.
> 
> [modular_tree_4_0_2c_windows.zip](https://github.com/MaximeHerpin/modular_tree/files/8989346/modular_tree_4_0_2c_windows.zip)
> 
> Setting up a fork at https://github.com/steven-ray/modular_tree so I can track my changes.

this one worked for me in 3.2 only thing that doesn't work it seems is the presets?

**Comment by ShengzhiWu** [comment]
Great work. Thank you very much.

> Hi ecker00,
> 
> I have enabled the issues tab in my fork of this repo. In looking at your log, I see part of the path includes`modular_tree-master`. This tells me you probably downloaded the .zip file of the entire repo from github (using the "download .zip" from the green "Code" button on the main page). This will get you the entire repo (unbuilt) which won't work in blender as is (you would need to build it and package it first).
> 
> I recommend removing that from blender, then going to the releases page at https://github.com/steven-ray/modular_tree/releases and download one of the appropriate built releases from there (e.g. modular_tree_4_0_2_1a_windows.zip) and try installing/enabling that.
> 
> Hope that helps!

**Comment by sunkper** [comment]
Heads-up for Blender 3.4. https://developer.blender.org/T101259

The new patch makes node search to pull custom nodes from add-ons in other node editors.

In short there was an error in Blender's custom node Python template (which is now corrected), and apparently it only needs a simple fix from add-on side.

https://developer.blender.org/T101259#1423759

**Comment by maljos** [comment]
**### Addon no enable in Linux Mint 21.1**
Blender 3.2.2

Error: addon not loaded: 'modular_tree'
cause: cannot import name 'm_tree' from partially initialized module 'modular_tree' (most likely due to a circular import) (/home/miro360/.config/blender/3.2/scripts/addons/modular_tree/__init__.py)
